// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ĐTSDay9Lesson.Models;

#nullable disable

namespace ĐTSDay9Lesson.Migrations
{
    [DbContext(typeof(DtsCFContext))]
    partial class CDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ĐTSDay9Lesson.Models.DtsLoaiSanPham", b =>
                {
                    b.Property<int>("DTSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DTSId"));

                    b.Property<string>("DTSMaLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DTSTenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DTSTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("DTSId");

                    b.HasIndex("DTSMaLoai")
                        .IsUnique();

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("ĐTSDay9Lesson.Models.DtsSanPham", b =>
                {
                    b.Property<int>("DTSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DTSId"));

                    b.Property<decimal>("DTSDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DTSHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DTSLoaiSanPhamDTSId")
                        .HasColumnType("int");

                    b.Property<long>("DTSLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<string>("DTSMaSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DTSSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("DTSTenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DTSId");

                    b.HasIndex("DTSLoaiSanPhamDTSId");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("ĐTSDay9Lesson.Models.DtsSanPham", b =>
                {
                    b.HasOne("ĐTSDay9Lesson.Models.DtsLoaiSanPham", "DTSLoaiSanPham")
                        .WithMany("DTSSanPhams")
                        .HasForeignKey("DTSLoaiSanPhamDTSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DTSLoaiSanPham");
                });

            modelBuilder.Entity("ĐTSDay9Lesson.Models.DtsLoaiSanPham", b =>
                {
                    b.Navigation("DTSSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
